/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProjekteRouteImport } from './routes/_authenticated/projekte'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBerichteRouteImport } from './routes/_authenticated/berichte'
import { Route as AuthenticatedAnalysenIndexRouteImport } from './routes/_authenticated/analysen.index'
import { Route as AuthenticatedAnalysenNeuRouteImport } from './routes/_authenticated/analysen.neu'
import { Route as AuthenticatedAnalysenIdRouteImport } from './routes/_authenticated/analysen.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteRoute = AuthenticatedProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerichteRoute = AuthenticatedBerichteRouteImport.update({
  id: '/berichte',
  path: '/berichte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysenIndexRoute =
  AuthenticatedAnalysenIndexRouteImport.update({
    id: '/analysen/',
    path: '/analysen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysenNeuRoute =
  AuthenticatedAnalysenNeuRouteImport.update({
    id: '/analysen/neu',
    path: '/analysen/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysenIdRoute = AuthenticatedAnalysenIdRouteImport.update({
  id: '/analysen/$id',
  path: '/analysen/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/berichte': typeof AuthenticatedBerichteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte': typeof AuthenticatedProjekteRoute
  '/team': typeof AuthenticatedTeamRoute
  '/analysen/$id': typeof AuthenticatedAnalysenIdRoute
  '/analysen/neu': typeof AuthenticatedAnalysenNeuRoute
  '/analysen/': typeof AuthenticatedAnalysenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/berichte': typeof AuthenticatedBerichteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte': typeof AuthenticatedProjekteRoute
  '/team': typeof AuthenticatedTeamRoute
  '/analysen/$id': typeof AuthenticatedAnalysenIdRoute
  '/analysen/neu': typeof AuthenticatedAnalysenNeuRoute
  '/analysen': typeof AuthenticatedAnalysenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/berichte': typeof AuthenticatedBerichteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/projekte': typeof AuthenticatedProjekteRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/analysen/$id': typeof AuthenticatedAnalysenIdRoute
  '/_authenticated/analysen/neu': typeof AuthenticatedAnalysenNeuRoute
  '/_authenticated/analysen/': typeof AuthenticatedAnalysenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/berichte'
    | '/dashboard'
    | '/einstellungen'
    | '/projekte'
    | '/team'
    | '/analysen/$id'
    | '/analysen/neu'
    | '/analysen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/berichte'
    | '/dashboard'
    | '/einstellungen'
    | '/projekte'
    | '/team'
    | '/analysen/$id'
    | '/analysen/neu'
    | '/analysen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/berichte'
    | '/_authenticated/dashboard'
    | '/_authenticated/einstellungen'
    | '/_authenticated/projekte'
    | '/_authenticated/team'
    | '/_authenticated/analysen/$id'
    | '/_authenticated/analysen/neu'
    | '/_authenticated/analysen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte': {
      id: '/_authenticated/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof AuthenticatedProjekteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/berichte': {
      id: '/_authenticated/berichte'
      path: '/berichte'
      fullPath: '/berichte'
      preLoaderRoute: typeof AuthenticatedBerichteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/': {
      id: '/_authenticated/analysen/'
      path: '/analysen'
      fullPath: '/analysen/'
      preLoaderRoute: typeof AuthenticatedAnalysenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/neu': {
      id: '/_authenticated/analysen/neu'
      path: '/analysen/neu'
      fullPath: '/analysen/neu'
      preLoaderRoute: typeof AuthenticatedAnalysenNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/$id': {
      id: '/_authenticated/analysen/$id'
      path: '/analysen/$id'
      fullPath: '/analysen/$id'
      preLoaderRoute: typeof AuthenticatedAnalysenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBerichteRoute: typeof AuthenticatedBerichteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedProjekteRoute: typeof AuthenticatedProjekteRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAnalysenIdRoute: typeof AuthenticatedAnalysenIdRoute
  AuthenticatedAnalysenNeuRoute: typeof AuthenticatedAnalysenNeuRoute
  AuthenticatedAnalysenIndexRoute: typeof AuthenticatedAnalysenIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBerichteRoute: AuthenticatedBerichteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedProjekteRoute: AuthenticatedProjekteRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAnalysenIdRoute: AuthenticatedAnalysenIdRoute,
  AuthenticatedAnalysenNeuRoute: AuthenticatedAnalysenNeuRoute,
  AuthenticatedAnalysenIndexRoute: AuthenticatedAnalysenIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
