/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformReglementeRouteImport } from './routes/platform.reglemente'
import { Route as PlatformRegionenRouteImport } from './routes/platform.regionen'
import { Route as PlatformOrganisationenRouteImport } from './routes/platform.organisationen'
import { Route as PlatformBenutzerRouteImport } from './routes/platform.benutzer'
import { Route as AuthenticatedWissenRouteImport } from './routes/_authenticated/wissen'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedProjekteRouteImport } from './routes/_authenticated/projekte'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedDokumentationRouteImport } from './routes/_authenticated/dokumentation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedAnalysenIndexRouteImport } from './routes/_authenticated/analysen.index'
import { Route as AuthenticatedFeedbackIdRouteImport } from './routes/_authenticated/feedback.$id'
import { Route as AuthenticatedAnalysenKarteRouteImport } from './routes/_authenticated/analysen.karte'
import { Route as AuthenticatedAnalysenIdRouteImport } from './routes/_authenticated/analysen.$id'
import { Route as AuthenticatedAnalysenIdBerichtRouteImport } from './routes/_authenticated/analysen.$id.bericht'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformReglementeRoute = PlatformReglementeRouteImport.update({
  id: '/reglemente',
  path: '/reglemente',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformRegionenRoute = PlatformRegionenRouteImport.update({
  id: '/regionen',
  path: '/regionen',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOrganisationenRoute = PlatformOrganisationenRouteImport.update({
  id: '/organisationen',
  path: '/organisationen',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformBenutzerRoute = PlatformBenutzerRouteImport.update({
  id: '/benutzer',
  path: '/benutzer',
  getParentRoute: () => PlatformRoute,
} as any)
const AuthenticatedWissenRoute = AuthenticatedWissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteRoute = AuthenticatedProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumentationRoute =
  AuthenticatedDokumentationRouteImport.update({
    id: '/dokumentation',
    path: '/dokumentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysenIndexRoute =
  AuthenticatedAnalysenIndexRouteImport.update({
    id: '/analysen/',
    path: '/analysen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackIdRoute = AuthenticatedFeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysenKarteRoute =
  AuthenticatedAnalysenKarteRouteImport.update({
    id: '/analysen/karte',
    path: '/analysen/karte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalysenIdRoute = AuthenticatedAnalysenIdRouteImport.update({
  id: '/analysen/$id',
  path: '/analysen/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysenIdBerichtRoute =
  AuthenticatedAnalysenIdBerichtRouteImport.update({
    id: '/bericht',
    path: '/bericht',
    getParentRoute: () => AuthenticatedAnalysenIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/platform': typeof PlatformRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokumentation': typeof AuthenticatedDokumentationRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte': typeof AuthenticatedProjekteRoute
  '/team': typeof AuthenticatedTeamRoute
  '/wissen': typeof AuthenticatedWissenRoute
  '/platform/benutzer': typeof PlatformBenutzerRoute
  '/platform/organisationen': typeof PlatformOrganisationenRoute
  '/platform/regionen': typeof PlatformRegionenRoute
  '/platform/reglemente': typeof PlatformReglementeRoute
  '/platform/': typeof PlatformIndexRoute
  '/analysen/$id': typeof AuthenticatedAnalysenIdRouteWithChildren
  '/analysen/karte': typeof AuthenticatedAnalysenKarteRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/analysen/': typeof AuthenticatedAnalysenIndexRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/analysen/$id/bericht': typeof AuthenticatedAnalysenIdBerichtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dokumentation': typeof AuthenticatedDokumentationRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte': typeof AuthenticatedProjekteRoute
  '/team': typeof AuthenticatedTeamRoute
  '/wissen': typeof AuthenticatedWissenRoute
  '/platform/benutzer': typeof PlatformBenutzerRoute
  '/platform/organisationen': typeof PlatformOrganisationenRoute
  '/platform/regionen': typeof PlatformRegionenRoute
  '/platform/reglemente': typeof PlatformReglementeRoute
  '/platform': typeof PlatformIndexRoute
  '/analysen/$id': typeof AuthenticatedAnalysenIdRouteWithChildren
  '/analysen/karte': typeof AuthenticatedAnalysenKarteRoute
  '/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/analysen': typeof AuthenticatedAnalysenIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/analysen/$id/bericht': typeof AuthenticatedAnalysenIdBerichtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/platform': typeof PlatformRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dokumentation': typeof AuthenticatedDokumentationRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/projekte': typeof AuthenticatedProjekteRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/wissen': typeof AuthenticatedWissenRoute
  '/platform/benutzer': typeof PlatformBenutzerRoute
  '/platform/organisationen': typeof PlatformOrganisationenRoute
  '/platform/regionen': typeof PlatformRegionenRoute
  '/platform/reglemente': typeof PlatformReglementeRoute
  '/platform/': typeof PlatformIndexRoute
  '/_authenticated/analysen/$id': typeof AuthenticatedAnalysenIdRouteWithChildren
  '/_authenticated/analysen/karte': typeof AuthenticatedAnalysenKarteRoute
  '/_authenticated/feedback/$id': typeof AuthenticatedFeedbackIdRoute
  '/_authenticated/analysen/': typeof AuthenticatedAnalysenIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/analysen/$id/bericht': typeof AuthenticatedAnalysenIdBerichtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/platform'
    | '/reset-password'
    | '/dashboard'
    | '/dokumentation'
    | '/einstellungen'
    | '/projekte'
    | '/team'
    | '/wissen'
    | '/platform/benutzer'
    | '/platform/organisationen'
    | '/platform/regionen'
    | '/platform/reglemente'
    | '/platform/'
    | '/analysen/$id'
    | '/analysen/karte'
    | '/feedback/$id'
    | '/analysen/'
    | '/feedback/'
    | '/analysen/$id/bericht'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/dokumentation'
    | '/einstellungen'
    | '/projekte'
    | '/team'
    | '/wissen'
    | '/platform/benutzer'
    | '/platform/organisationen'
    | '/platform/regionen'
    | '/platform/reglemente'
    | '/platform'
    | '/analysen/$id'
    | '/analysen/karte'
    | '/feedback/$id'
    | '/analysen'
    | '/feedback'
    | '/analysen/$id/bericht'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/platform'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/dokumentation'
    | '/_authenticated/einstellungen'
    | '/_authenticated/projekte'
    | '/_authenticated/team'
    | '/_authenticated/wissen'
    | '/platform/benutzer'
    | '/platform/organisationen'
    | '/platform/regionen'
    | '/platform/reglemente'
    | '/platform/'
    | '/_authenticated/analysen/$id'
    | '/_authenticated/analysen/karte'
    | '/_authenticated/feedback/$id'
    | '/_authenticated/analysen/'
    | '/_authenticated/feedback/'
    | '/_authenticated/analysen/$id/bericht'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/reglemente': {
      id: '/platform/reglemente'
      path: '/reglemente'
      fullPath: '/platform/reglemente'
      preLoaderRoute: typeof PlatformReglementeRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/regionen': {
      id: '/platform/regionen'
      path: '/regionen'
      fullPath: '/platform/regionen'
      preLoaderRoute: typeof PlatformRegionenRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/organisationen': {
      id: '/platform/organisationen'
      path: '/organisationen'
      fullPath: '/platform/organisationen'
      preLoaderRoute: typeof PlatformOrganisationenRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/benutzer': {
      id: '/platform/benutzer'
      path: '/benutzer'
      fullPath: '/platform/benutzer'
      preLoaderRoute: typeof PlatformBenutzerRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_authenticated/wissen': {
      id: '/_authenticated/wissen'
      path: '/wissen'
      fullPath: '/wissen'
      preLoaderRoute: typeof AuthenticatedWissenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte': {
      id: '/_authenticated/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof AuthenticatedProjekteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumentation': {
      id: '/_authenticated/dokumentation'
      path: '/dokumentation'
      fullPath: '/dokumentation'
      preLoaderRoute: typeof AuthenticatedDokumentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/': {
      id: '/_authenticated/analysen/'
      path: '/analysen'
      fullPath: '/analysen/'
      preLoaderRoute: typeof AuthenticatedAnalysenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/$id': {
      id: '/_authenticated/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof AuthenticatedFeedbackIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/karte': {
      id: '/_authenticated/analysen/karte'
      path: '/analysen/karte'
      fullPath: '/analysen/karte'
      preLoaderRoute: typeof AuthenticatedAnalysenKarteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/$id': {
      id: '/_authenticated/analysen/$id'
      path: '/analysen/$id'
      fullPath: '/analysen/$id'
      preLoaderRoute: typeof AuthenticatedAnalysenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysen/$id/bericht': {
      id: '/_authenticated/analysen/$id/bericht'
      path: '/bericht'
      fullPath: '/analysen/$id/bericht'
      preLoaderRoute: typeof AuthenticatedAnalysenIdBerichtRouteImport
      parentRoute: typeof AuthenticatedAnalysenIdRoute
    }
  }
}

interface AuthenticatedAnalysenIdRouteChildren {
  AuthenticatedAnalysenIdBerichtRoute: typeof AuthenticatedAnalysenIdBerichtRoute
}

const AuthenticatedAnalysenIdRouteChildren: AuthenticatedAnalysenIdRouteChildren =
  {
    AuthenticatedAnalysenIdBerichtRoute: AuthenticatedAnalysenIdBerichtRoute,
  }

const AuthenticatedAnalysenIdRouteWithChildren =
  AuthenticatedAnalysenIdRoute._addFileChildren(
    AuthenticatedAnalysenIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDokumentationRoute: typeof AuthenticatedDokumentationRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedProjekteRoute: typeof AuthenticatedProjekteRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWissenRoute: typeof AuthenticatedWissenRoute
  AuthenticatedAnalysenIdRoute: typeof AuthenticatedAnalysenIdRouteWithChildren
  AuthenticatedAnalysenKarteRoute: typeof AuthenticatedAnalysenKarteRoute
  AuthenticatedFeedbackIdRoute: typeof AuthenticatedFeedbackIdRoute
  AuthenticatedAnalysenIndexRoute: typeof AuthenticatedAnalysenIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDokumentationRoute: AuthenticatedDokumentationRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedProjekteRoute: AuthenticatedProjekteRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWissenRoute: AuthenticatedWissenRoute,
  AuthenticatedAnalysenIdRoute: AuthenticatedAnalysenIdRouteWithChildren,
  AuthenticatedAnalysenKarteRoute: AuthenticatedAnalysenKarteRoute,
  AuthenticatedFeedbackIdRoute: AuthenticatedFeedbackIdRoute,
  AuthenticatedAnalysenIndexRoute: AuthenticatedAnalysenIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteChildren {
  PlatformBenutzerRoute: typeof PlatformBenutzerRoute
  PlatformOrganisationenRoute: typeof PlatformOrganisationenRoute
  PlatformRegionenRoute: typeof PlatformRegionenRoute
  PlatformReglementeRoute: typeof PlatformReglementeRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformBenutzerRoute: PlatformBenutzerRoute,
  PlatformOrganisationenRoute: PlatformOrganisationenRoute,
  PlatformRegionenRoute: PlatformRegionenRoute,
  PlatformReglementeRoute: PlatformReglementeRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlatformRoute: PlatformRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
